import { useState, useMemo } from "react";
import { showErrorDialog } from "../components/Dialog";
import { showSuccessToast, showErrorToast } from "../components/Toast";

async function callGroqToBuildSubject(apiKey, subjectName, subjectCode, syllabusText) {
  const systemPrompt = `You are an expert curriculum builder. Your task is to output a fully populated study guide JSON file for the subject "${subjectName}" (Code: "${subjectCode}").
Generate exactly 5 comprehensive study guide questions and answers based on the syllabus/topics provided, and exactly 5 interactive multiple-choice quiz questions.

The output must be a single raw JSON object matching this schema:
{
  "subjectCode": "String",
  "subjectName": "String",
  "subjectTitle": "String",
  "description": "String description summarizing the content",
  "stats": [
    { "value": "5", "label": "Questions" },
    { "value": "5", "label": "MCQs" }
  ],
  "categories": [
    { "id": "all", "label": "All Topics" },
    { "id": "core", "label": "Core Content" }
  ],
  "papers": ["Mock Exam"],
  "questions": [
    {
      "n": 1,
      "hot": true,
      "cat": "core",
      "unit": "Core Unit",
      "text": "Question title here?",
      "papers": ["Mock Exam"],
      "freq": 3,
      "answer": "Detailed answer in markdown formatting. Clean and formatting-heavy.",
      "diagram": "Mermaid diagram code if applicable (e.g. graph TD) or null"
    }
  ],
  "quiz": [
    {
      "question": "Question statement?",
      "options": ["Option A", "Option B", "Option C", "Option D"],
      "answer": "The exact correct option string verbatim from options",
      "explanation": "Why this option is correct."
    }
  ]
}

Ensure all answers are detailed, clear, and make heavy use of bullet points and bold styling. 
Return ONLY the raw JSON block without backticks or any conversation.`;

  const userPrompt = `Generate a study guide JSON for:
Subject: ${subjectName} (${subjectCode})
Syllabus / Topics to cover:
${syllabusText}`;

  const res = await fetch("https://api.groq.com/openai/v1/chat/completions", {
    method: "POST",
    headers: { "Content-Type": "application/json", "Authorization": `Bearer ${apiKey}` },
    body: JSON.stringify({
      model: "llama-3.3-70b-versatile",
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt }
      ],
      temperature: 0.6,
      max_tokens: 4000
    })
  });

  if (!res.ok) {
    const err = await res.json();
    throw new Error(err.error?.message || "Groq API error");
  }
  const data = await res.json();
  const rawText = data.choices[0].message.content.trim();
  const jsonText = rawText.replace(/^```json\s*/i, '').replace(/```$/, '').trim();
  return JSON.parse(jsonText);
}

export function AiBuilderView({ apiKey, onSubjectGenerated }) {
  const [subjName, setSubjName] = useState("Distributed Systems");
  const [subjCode, setSubjCode] = useState("MCS-232");
  const [syllabus, setSyllabus] = useState("Unit 1: Introduction to Distributed Systems, Resource sharing, Challenges\nUnit 2: System Models, Architectural & Fundamental Models\nUnit 3: Interprocess Communication, APIs, Multicast communication");
  
  const [promptCopied, setPromptCopied] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState("");

  const systemPromptTemplate = useMemo(() => {
    return `You are a professional curriculum builder. Create a study guide JSON for the subject "${subjName}" (Code: "${subjCode}").
Integrate this syllabus:
"${syllabus}"

Provide exactly 5 highly comprehensive study guide questions/answers covering these topics, and exactly 5 interactive multiple-choice questions for practice.

Return ONLY a valid JSON object matching the StudyMate schema below:
{
  "subjectCode": "${subjCode}",
  "subjectName": "${subjName}",
  "subjectTitle": "Syllabus Study Guide",
  "description": "Interactive study guide generated by AI.",
  "stats": [
    { "value": "5", "label": "Questions" },
    { "value": "5", "label": "MCQs" }
  ],
  "categories": [
    { "id": "all", "label": "All Topics" },
    { "id": "core", "label": "Core Content" }
  ],
  "papers": ["Mock Test"],
  "questions": [
    {
      "n": 1,
      "hot": true,
      "cat": "core",
      "unit": "Core Unit",
      "text": "Question text here?",
      "papers": ["Mock Test"],
      "freq": 3,
      "answer": "Detailed answer in markdown. Heavy list formatting and bold titles.",
      "diagram": "Mermaid diagram code if applicable (e.g. graph TD) or null"
    }
  ],
  "quiz": [
    {
      "question": "Question statement?",
      "options": ["A", "B", "C", "D"],
      "answer": "Verbatim correct option string",
      "explanation": "Why this option is correct."
    }
  ]
}

No conversations, no markdown code block surrounding the JSON (e.g. no \`\`\`json block), just pure raw JSON.`;
  }, [subjName, subjCode, syllabus]);

  const handleCopyPrompt = () => {
    navigator.clipboard.writeText(systemPromptTemplate);
    setPromptCopied(true);
    showSuccessToast("Prompt Copied to Clipboard!");
    setTimeout(() => setPromptCopied(false), 2000);
  };

  const handleDirectGenerate = async () => {
    if (!apiKey) {
      showErrorDialog("API Key Required", "Please set your Groq API key in Settings (⚙️ icon) first.");
      return;
    }
    setGenerating(true);
    setError("");
    try {
      const parsedJson = await callGroqToBuildSubject(apiKey, subjName, subjCode, syllabus);
      onSubjectGenerated(parsedJson);
      showSuccessToast(`Generated: ${parsedJson.subjectName}`);
    } catch (err) {
      console.error(err);
      setError(err.message || "Failed to generate subject JSON.");
      showErrorToast("Generation Failed");
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div className="glass-panel fade-in" style={{ borderRadius: 16, padding: "1.5rem", maxWidth: 640, margin: "0 auto" }}>
      <h2 style={{ fontSize: 18, fontWeight: 700, color: "var(--color-text-primary)", marginBottom: 8 }}>✨ AI Subject Builder</h2>
      <p style={{ fontSize: 12, color: "var(--color-text-tertiary)", marginBottom: 20 }}>
        Create dynamic study guides and quizzes for any subject. Build a copyable LLM prompt or generate it directly inside the app using Groq.
      </p>

      {error && (
        <div style={{ padding: "12px", background: "rgba(239, 68, 68, 0.08)", border: "1px solid #ef4444", borderRadius: 8, color: "#ef4444", fontSize: 12, marginBottom: 16 }}>
          ⚠️ Generation Error: {error}
        </div>
      )}

      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12, marginBottom: 14 }}>
        <div>
          <label style={{ display: "block", fontSize: 11, fontWeight: 600, color: "var(--color-text-tertiary)", textTransform: "uppercase", marginBottom: 6 }}>Subject Name</label>
          <input
            type="text"
            value={subjName}
            onChange={e => setSubjName(e.target.value)}
            style={{ width: "100%", padding: "10px", borderRadius: 8, fontSize: 13, background: "var(--color-background-secondary)", color: "var(--color-text-primary)", border: "1px solid var(--color-border-secondary)", outline: "none" }}
          />
        </div>
        <div>
          <label style={{ display: "block", fontSize: 11, fontWeight: 600, color: "var(--color-text-tertiary)", textTransform: "uppercase", marginBottom: 6 }}>Subject Code</label>
          <input
            type="text"
            value={subjCode}
            onChange={e => setSubjCode(e.target.value)}
            style={{ width: "100%", padding: "10px", borderRadius: 8, fontSize: 13, background: "var(--color-background-secondary)", color: "var(--color-text-primary)", border: "1px solid var(--color-border-secondary)", outline: "none" }}
          />
        </div>
      </div>

      <div style={{ marginBottom: 20 }}>
        <label style={{ display: "block", fontSize: 11, fontWeight: 600, color: "var(--color-text-tertiary)", textTransform: "uppercase", marginBottom: 6 }}>Topics / Syllabus</label>
        <textarea
          rows={5}
          value={syllabus}
          onChange={e => setSyllabus(e.target.value)}
          placeholder="List units, chapters, or specific topics to include..."
          style={{ width: "100%", padding: "10px", borderRadius: 8, fontSize: 13, background: "var(--color-background-secondary)", color: "var(--color-text-primary)", border: "1px solid var(--color-border-secondary)", outline: "none", resize: "vertical", fontFamily: "inherit", lineHeight: 1.5 }}
        />
      </div>

      <div style={{ display: "flex", gap: 10, justifyContent: "flex-end", flexWrap: "wrap" }}>
        <button
          onClick={handleCopyPrompt}
          style={{
            padding: "11px 20px", fontSize: 13, borderRadius: 8, fontWeight: 600, cursor: "pointer",
            background: "var(--color-background-secondary)", color: "var(--color-text-secondary)", border: "1px solid var(--color-border-secondary)"
          }}
        >
          {promptCopied ? "✓ Prompt Copied!" : "📋 Copy Prompt for LLM"}
        </button>
        <button
          onClick={handleDirectGenerate}
          disabled={generating}
          style={{
            padding: "11px 20px", fontSize: 13, borderRadius: 8, fontWeight: 600, cursor: "pointer",
            background: "var(--color-accent)", color: "var(--color-accent-text)", border: "none",
            display: "flex", alignItems: "center", gap: 6
          }}
        >
          {generating ? (
            <>
              <span className="spin">⟳</span> Generating study guide...
            </>
          ) : (
            "✨ Generate with Groq"
          )}
        </button>
      </div>

      {generating && (
        <p style={{ fontSize: 11, color: "var(--color-text-tertiary)", marginTop: 12, textAlign: "right" }}>
          Llama 3 is crunching the topics. This might take up to 20 seconds.
        </p>
      )}
    </div>
  );
}

export default function BuilderScreen({
  apiKey,
  onSubjectGenerated,
  setScreen,
  theme,
  setTheme
}) {
  return (
    <div style={{ minHeight: "100vh", display: "flex", flexDirection: "column", background: "var(--color-bg-body)" }}>
      {/* Header bar */}
      <header style={{
        background: "var(--color-header-gradient)",
        color: "#ffffff",
        padding: "16px",
        boxShadow: "0 2px 8px rgba(0,0,0,0.1)",
        position: "sticky",
        top: 0,
        zIndex: 11,
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between"
      }}>
        <button
          onClick={() => setScreen("home")}
          style={{
            background: "transparent",
            border: "none",
            color: "#ffffff",
            fontSize: "20px",
            fontWeight: "bold",
            cursor: "pointer",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            padding: "4px 8px",
            minWidth: "44px",
            minHeight: "44px"
          }}
        >
          ←
        </button>

        <h2 style={{ fontSize: "16px", fontWeight: 700 }}>AI Subject Builder</h2>

        <button
          onClick={() => setTheme(t => t === "light" ? "dark" : "light")}
          style={{
            background: "transparent",
            border: "none",
            color: "#ffffff",
            fontSize: "18px",
            cursor: "pointer",
            padding: "8px",
            minWidth: "44px",
            minHeight: "44px"
          }}
        >
          {theme === "light" ? "🌙" : "☀️"}
        </button>
      </header>

      <main style={{ flex: 1, padding: "20px 16px" }}>
        <AiBuilderView apiKey={apiKey} onSubjectGenerated={(newSub) => {
          onSubjectGenerated(newSub);
          setScreen("subject");
        }} />
      </main>
    </div>
  );
}
